import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import "./globals.css";
import Footer from "@/components/footer";
import { DisplayGrid12 } from "@/components/layout/grid12";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${spaceGrotesk.variable} max-w-screen overflow-x-hidden scroll-smooth space-grotesk`}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        {/* <img
          src="./img/test.png"
          className="fixed top-0 left-0 w-full h-full -z-20 pointer-events-none select-none"
          alt=""
        /> */}
        <DisplayGrid12 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
